=== BartoszKacperski/pkck/2/BookStore.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:type="http://www.example.org/types" targetNamespace="http://www.example.org/types" elementFormDefault="qualified">

    <xs:element name="root">
    <xs:complexType >
        <xs:sequence>
            <xs:element name="info" type="type:infoType" />
            <xs:element name="bookstore" type="type:bookstoreType" />
        </xs:sequence>
    </xs:complexType>
    </xs:element>

    <xs:complexType name="infoType">
        <xs:sequence>
            <xs:element name="owners" type="type:ownersType"/>
            <xs:element name="description" type="xs:normalizedString" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ownersType">
        <xs:sequence>
            <xs:element name="owner" type="xs:normalizedString" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bookstoreType">
        <xs:sequence>
            <xs:element name="authors" type="type:authorsType"/>
            <xs:element name="books" type="type:booksType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="authorsType">
        <xs:sequence>
            <xs:element name="author" type="type:authorType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="authorType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="pseudonym" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="authorId" type="xs:token" use="required" />
    </xs:complexType>

    <xs:complexType name="booksType">
        <xs:sequence>
            <xs:element name="book" type="type:bookType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="releaseDate" type="type:releaseDateType"/>
        </xs:sequence>
        <xs:attribute name="authorId" type="xs:token" use="required"/>
        <xs:attribute name="bookId" type="xs:token" use="required"/>
        <xs:attribute name="category" type="xs:token" use="required"/>
        <xs:attribute name="pages" type="xs:positiveInteger"/>
        <xs:attribute name="rating" type="xs:token" default="brak"/>
    </xs:complexType>

    <xs:complexType name="releaseDateType">
        <xs:sequence>
            <xs:element name="year" type="xs:gYear"/>
            <xs:element name="month" type="xs:gMonth"/>
            <xs:element name="day" type="xs:gDay"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== BartoszKacperski/pkck/2/BookStore.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="stylesheet.css"?>

<root xmlns="http://www.example.org/types"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/types BookStore.xsd">
    <info>
        <owners>
            <owner>Bartosz Kacperski</owner>
            <owner>Paweł Pomarański</owner>
        </owners>
        <description>
            Dokument zawiera katalog książek w bibliotece
        </description>
    </info>
    <bookstore>
        <authors>
            <author authorId="a1">
                <firstName>Stephen</firstName>
                <lastName>King</lastName>
                <pseudonym>Richard Bachman</pseudonym>
            </author>
            <author authorId="a2">
                <firstName>Arthur</firstName>
                <firstName>Conan</firstName>
                <lastName>Doyle</lastName>
            </author>
            <author authorId="a3">
                <firstName>Harlan</firstName>
                <lastName>Coben</lastName>
            </author>
        </authors>
        <books>
            <book bookId="b1" authorId="a1" category="dramat" pages="200" rating="brak">
                <title>17 podniebnych koszmarów</title>
                <releaseDate>
                    <year>1996</year>
                    <month>--02</month>
                    <day>---19</day>
                </releaseDate>
            </book>
            <book bookId="b2" authorId="a1" category="horror" rating="2">
                <title>999 tom 1</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b3" authorId="a1" category="horror" pages="364" rating="brak">
                <title>Arcydzieła czarnego kryminału</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b4" authorId="a1" category="horror" rating="4">
                <title>Ballada o celnym strzale</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b5" authorId="a1" category="horror" rating="brak">
                <title>Bastion</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b6" authorId="a1" category="horror" rating="2">
                <title>Bazar złych snów</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b7" authorId="a1" category="horror" rating="brak">
                <title>Bezsenność</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b8" authorId="a1" category="horror" rating="1">
                <title>Buick 8</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b9" authorId="a1" category="horror" rating="4">
                <title>Carrie</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b10" authorId="a1" category="horror" rating="brak">
                <title>Christine</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b11" authorId="a1" category="horror" rating="4">
                <title>Cmętarz zwieżąt</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---21</day>
                </releaseDate>
            </book>
            <book bookId="b12" authorId="a1" category="horror" rating="brak">
                <title>Czarnoksiężnik i kryształ</title>
                <releaseDate>
                    <year>1977</year>
                    <month>--05</month>
                    <day>---02</day>
                </releaseDate>
            </book>

            <book bookId="b13" authorId="a1" category="akcja" rating="2">
                <title>Sherlock Holmes</title>
                <releaseDate>
                    <year>2001</year>
                    <month>--12</month>
                    <day>---25</day>
                </releaseDate>
            </book>

            <book bookId="b14" authorId="a3" category="kryminał" rating="brak">
                <title>Już mnie nie oszukasz</title>
                <releaseDate>
                    <year>2016</year>
                    <month>--12</month>
                    <day>---25</day>
                </releaseDate>
            </book>
            <book bookId="b15" authorId="a3" category="powieść" rating="5">
                <title>Aż śmierć nas rozłączy</title>
                <releaseDate>
                    <year>1999</year>
                    <month>--02</month>
                    <day>---22</day>
                </releaseDate>
            </book>
            <book bookId="b16" authorId="a3" category="powieść" rating="3">
                <title>Bez pożegnania</title>
                <releaseDate>
                    <year>1999</year>
                    <month>--02</month>
                    <day>---03</day>
                </releaseDate>
            </book>
            <book bookId="b17" authorId="a3" category="powieść" rating="1">
                <title>Aż śmierć nas rozłączy</title>
                <releaseDate>
                    <year>1999</year>
                    <month>--02</month>
                    <day>---22</day>
                </releaseDate>
            </book>
            <book bookId="b18" authorId="a3" category="powieść" rating="2">
                <title>Bez skrupułów</title>
                <releaseDate>
                    <year>1999</year>
                    <month>--02</month>
                    <day>---22</day>
                </releaseDate>
            </book>
            <book bookId="b19" authorId="a3" category="powieść" rating="5">
                <title>Bez śladu</title>
                <releaseDate>
                    <year>1999</year>
                    <month>--02</month>
                    <day>---22</day>
                </releaseDate>
            </book>
            <book bookId="b20" authorId="a3" category="powieść" rating="brak">
                <title>Błękitna krew</title>
                <releaseDate>
                    <year>1999</year>
                    <month>--02</month>
                    <day>---22</day>
                </releaseDate>
            </book>
        </books>
    </bookstore>
</root>
